/**
 * Generates src/styles/tokens.css from design-tokens.js at repo root
 * Source of truth: ../design-tokens.js
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { designTokens } from '../design-tokens.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '../src/styles/tokens.css');

const { colors, typography, spacing, radius, shadows } = designTokens.theme;

function emitThemeVars(theme, prefix = '') {
  const c = colors[theme];
  const s = shadows[theme];
  const lines = [];

  lines.push(`  /* Background */`);
  lines.push(`  --color-bg-page: ${c.background.default};`);
  lines.push(`  --color-bg-surface: ${c.background.surface};`);
  lines.push(`  --color-bg-elevated: ${c.background.elevated};`);

  lines.push(`  /* Text */`);
  lines.push(`  --color-text-primary: ${c.text.primary};`);
  lines.push(`  --color-text-secondary: ${c.text.secondary};`);
  lines.push(`  --color-text-muted: ${c.text.muted};`);
  lines.push(`  --color-text-inverse: ${c.text.inverse};`);

  lines.push(`  /* Border */`);
  lines.push(`  --color-border-subtle: ${c.border.subtle};`);
  lines.push(`  --color-border-default: ${c.border.default};`);
  lines.push(`  --color-border-strong: ${c.border.strong};`);

  lines.push(`  /* Action (monochrome primary) */`);
  lines.push(`  --color-action-main: ${c.primary.main};`);
  lines.push(`  --color-action-hover: ${c.primary.hover};`);
  lines.push(`  --color-action-active: ${c.primary.active};`);
  lines.push(`  --color-action-disabled: ${c.primary.disabled};`);
  lines.push(`  --color-action-text: ${theme === 'light' ? c.text.inverse : c.text.inverse};`);

  lines.push(`  /* Semantic â€” success */`);
  lines.push(`  --color-success-bg: ${c.semantic.success.bg};`);
  lines.push(`  --color-success-text: ${c.semantic.success.text};`);
  lines.push(`  --color-success-border: ${c.semantic.success.border};`);

  lines.push(`  /* Semantic â€” error */`);
  lines.push(`  --color-error-bg: ${c.semantic.error.bg};`);
  lines.push(`  --color-error-text: ${c.semantic.error.text};`);
  lines.push(`  --color-error-border: ${c.semantic.error.border};`);

  lines.push(`  /* Semantic â€” warning */`);
  lines.push(`  --color-warning-bg: ${c.semantic.warning.bg};`);
  lines.push(`  --color-warning-text: ${c.semantic.warning.text};`);
  lines.push(`  --color-warning-border: ${c.semantic.warning.border};`);

  lines.push(`  /* Semantic â€” info */`);
  lines.push(`  --color-info-bg: ${c.semantic.info.bg};`);
  lines.push(`  --color-info-text: ${c.semantic.info.text};`);
  lines.push(`  --color-info-border: ${c.semantic.info.border};`);

  lines.push(`  /* Shadows */`);
  lines.push(`  --shadow-sm: ${s.sm};`);
  lines.push(`  --shadow-md: ${s.md};`);
  lines.push(`  --shadow-lg: ${s.lg};`);

  return lines.join('\n');
}

function emitSharedVars() {
  const lines = [];

  lines.push(`  /* Typography â€” Inter only */`);
  lines.push(`  --font-family-base: ${typography.fontFamily.base};`);
  lines.push(`  --font-family-heading: ${typography.fontFamily.heading};`);

  for (const [key, val] of Object.entries(typography.fontSize)) {
    lines.push(`  --font-size-${key}: ${val};`);
  }
  for (const [key, val] of Object.entries(typography.fontWeight)) {
    lines.push(`  --font-weight-${key}: ${val};`);
  }
  for (const [key, val] of Object.entries(typography.lineHeight)) {
    lines.push(`  --line-height-${key}: ${val};`);
  }

  lines.push(`  /* Spacing â€” 8pt grid */`);
  for (const [key, val] of Object.entries(spacing)) {
    lines.push(`  --space-${key}: ${val};`);
  }

  lines.push(`  /* Radius */`);
  for (const [key, val] of Object.entries(radius)) {
    lines.push(`  --radius-${key}: ${val};`);
  }

  lines.push(`  /* Z-index */`);
  lines.push(`  --z-dropdown: 100;`);
  lines.push(`  --z-modal: 400;`);
  lines.push(`  --z-toast: 500;`);

  return lines.join('\n');
}

const css = `/* ============================================================
   Strativy Minimalist Design System â€” CSS Custom Properties
   AUTO-GENERATED by scripts/generate-tokens.mjs
   Source: design-tokens.js at repo root
   Do not edit manually â€” run: npm run tokens
   ============================================================ */

:root {
${emitThemeVars('light')}
${emitSharedVars()}
}

.dark {
${emitThemeVars('dark')}
}
`;

writeFileSync(outPath, css, 'utf8');
console.log(`âœ“ Generated ${outPath}`);

